"""empty message

Revision ID: 34332e11bce3
Revises: 
Create Date: 2023-04-20 12:17:18.379513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34332e11bce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=75), nullable=False),
    sa.Column('email', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('com__profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('location', sa.String(length=50), nullable=False),
    sa.Column('about_me', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('twitter_url', sa.String(length=200), nullable=True),
    sa.Column('instagram_url', sa.String(length=200), nullable=True),
    sa.Column('facebook_url', sa.String(length=200), nullable=True),
    sa.Column('tiktok_url', sa.String(length=200), nullable=True),
    sa.Column('youtube_url', sa.String(length=200), nullable=True),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('com__profile')
    op.drop_table('comic')
    # ### end Alembic commands ###
